import { TPropStream } from "./interface/widget";
export declare type TDateInputType = "dd" | "mm" | "yyyy" | "yy";
export declare type TDateType = 'day' | 'month' | 'year';
export declare function dateInputIds(type: TDateType): "dd" | "mm" | "yyyy";
export declare function focusLastInput(dom: Element, id: string, focusedId?: TDateInputType): void;
export declare function handleRetreatOrLiteralAdvance(id: string, selfType: TDateInputType, streamValue: string, dom: Element, event: KeyboardEvent, literalKey: string, nextTargetType?: TDateInputType, prevTargetTyype?: TDateInputType): void;
export declare function resetInvalidValueStream(valid: boolean, date: string, year: string, month: string, day: string, valueStream: TPropStream): void;
export declare function appendZeroToDayMonth(valueStream: TPropStream): void;
export declare function validDateInputLengths(year: string, month: string, day: string): boolean;
export declare function validateCardDate(year: string, month: string, required: boolean, dom?: Element): boolean;
export declare function validateDate(year: string, month: string, day: string, required: boolean, dom?: Element): boolean;
export declare function handleDateChange(streamType: TPropStream, id: string, selfType: TDateInputType, dom: Element, targetType?: TDateInputType): void;
