
name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: publish to registry
        uses: actions/setup-node@v1
      - run: rm .npmrc
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc 
      - run: echo "@sdxmessaging:registry=https://npm.pkg.github.com" >> ~/.npmrc 
      - run: npm publish
